### ISSUE TITLE
Support for specifying a custom docker connection URI

### ISSUE THREAD

**Issue by mariuszste** [VirtCode/serene-aur#2]
It would be nice if we could specify a custom docker socket to use via env variables with support for more than just unix sockets (like TCP). Would replacing `Docker::connect_with_socket_defaults` with `Docker::connect_with_defaults` be enough or am I missing something? I've looked at the code and it doesn't seem to do anything hacky so I don't see why this couldn't work.

**Comment by VirtCode** [comment]
Yes, replacing that with any other `connect_with` method should just work, as all interfacing with the containers is done through this `Docker` instance. It would be nice if we could specify an url in the config (i.e. with `tcp://` or `unix://`) which would then be used. I might have a look at this later this week.

As for docker in docker, I think it's a really cool concept, but am unsure about it (see [this blogpost](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)). But if we can specify an url like above, we can easily create a second image which makes use of docker in docker.

**Comment by mariuszste** [comment]
yeah, I know that DinD has some nasty downsides, maybe I shouldn't have mentioned it. IMO adding support for connecting to different docker sockets should be the only concern. If someone crazy like me wants to run DinD it should be their problem, supporting it officially will just put unnecessary maintenance costs on you.

> we can easily create a second image which makes use of docker in docker.

What? Why would we need another image? What for? Docker already provides official dind images (`library/docker:dind`), if a user wants to they can just run that themselves and provide the URL to connect to it. The existing runner containers shouldn't care where they are running since as you mentioned "all interfacing with the containers is done through this Docker instance"

**Comment by mariuszste** [comment]
works, thank you
