### ISSUE TITLE
could not find .SRCINFO file in archive from container

### ISSUE THREAD

**Issue by dumbasPL** [VirtCode/serene-aur#8]
I'm getting
```
status:  fatal on publishing repository
message: could not find .SRCINFO file in archive from container
```
on some packages, removing and re-adding them seem to fix it temporarily

I've confirmed that `/app/sources/<package name>` has a `.SRCINFO` file and they build fine afterwards

**Comment by VirtCode** [comment]
yep, this is a result of building with an outdated container image, because I made some breaking changes in https://github.com/VirtCode/serene-aur/commit/cd53315f3c8c573691a83c92837c992fd58dcfa1, before it was just taking the built version from the container, but now it is taking the whole srcinfo (to account for pkgrel changes).

anyway, this is easily fixable by rebuilding the failing packages with `--clean` which recreates the container (with the newly pulled image), so 
```
serene build -c your-package
```
should fix it for that package.

Sorry, should've probably announced the breaking changes somehow, but that's kinda difficult without creating a new release.

**Comment by dumbasPL** [comment]
How about doing a clean build when the base container image changes? Or at least versioning the images so that you can bump a major version every time there is a breaking change and force a clean build on all packages using the old image.

**Comment by VirtCode** [comment]
True that would be a better idea, to somehow version the container images and comparing the version to the running server and recreating them if necessary. Will look into that before I push breaking changes next time.

I also should figure out some versioning strategy in general, at the moment it's a bit of a mess.

**Comment by VirtCode** [comment]
okay, i finally had some time on my hands and have now implemented a versioning strategy for this repo. This bring the following changes:
- a new tag will be created (by me) every time breaking changes are introduced between the cli, server, or runner
- the runner images are tagged with `edge-{version}`
- the server will make sure containers use the latest runner image tag
- the cli checks for server version conflicts on `list` and `info`, and prints a warning to tell the user to update

This means stuff like this should no longer happen in the future, as the server will update recreate the containers if needed. If you have set a runner image via an env, you should update this env to the new format (or just remove it if you are using the images from this repo's gh actions anyways)

Thanks again for bringing this to my attention. This has finally pushed me to do proper versioning there. The next bigger thing I will be working on will finally be automatic dependency resolving.

Also (if you are still using this anyways), these changes also add a new command `serene manage info`, with which you can have a look at some of your server's stats.

**Comment by dumbasPL** [comment]
> if you are still using this anyways

Yes, I've been dreaming of something like this for ages and almost started making my own at some point. I think the star counter is missing a few zeros if you ask me. Thanks for taking it seriously,
